# Generated by Django 5.0.1 on 2024-01-21 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='profeor',
            new_name='profesor',
        ),
    ]
